### ISSUE TITLE
Error on install

### ISSUE THREAD

**Issue by artmunro** [phra/loopback-angular2-boilerplate#10] opened 2016-06-09 21:14 UTC
Greetings,

I am in the process of putting together a boilerplate application for Angular 2 and Loopback.  I came across this repo and decided to give it a shot.  After doing "npm i" ... there is an error.  I think that a datasource must be setup/configured.  Thoughts?  I'm using the loopback-connector-postgresql

Thoughts?

Error Below ...
BTW .. latest Node 6.2.1

npm ERR! loopback-angular2-boilerplate@0.0.2 db-migrate-up: `node_modules/db-migrate/bin/db-migrate --config migrations/database.json --migrations-dir migrations/migrations --verbose up -e `cat server/datasources.json | grep -A 2 postgres | grep database | cut -d'"' -f 4``
npm ERR! Exit status 255
npm ERR!
npm ERR! Failed at the loopback-angular2-boilerplate@0.0.2 db-migrate-up script 'node_modules/db-migrate/bin/db-migrate --config migrations/database.json --migrations-dir migrations/migrations --verbose up -e `cat server/datasources.json | grep -A 2 postgres | grep database | cut -d'"' -f 4`'.

**Comment by phra** [comment] 2016-06-10 15:54
hi,

i was unable to reproduce this issue (did you have created the database in postgresql?)
instead i'm experiencing a bug with jspm (it's not finding the js files :-1: ).

ps: this boilerplate project is outdated, i.e:
- angular2 beta11 so you have to upgrade to latest angular2 rc release asap (there are breaking changes from beta to rc)
- loopback 2 (loopback 3 is coming)
- generations of angular2 code comes from a community contribution not merged in the upstream
- jspm is outdated and there are breaking changes

**Closed** 2016-06-22 21:11 UTC
Labels: wontfix
